insert into gem_weight(id, name, superior, anomalous, divergent, phantasmal) values(40, 'Wrath', 50, 100, 1, 0);
insert into gem_weight(id, name, superior, anomalous, divergent, phantasmal) values(5124, 'Shock Nova', 50, 50, 100, 0);
insert into gem_weight(id, name, superior, anomalous, divergent, phantasmal) values(765, 'Domination', 50, 100, 50, 10);
insert into gem_weight(id, name, superior, anomalous, divergent, phantasmal) values(5, 'Infused Channelling Support', 50, 100, 20, 0);
insert into gem_weight(id, name, superior, anomalous, divergent, phantasmal) values(85, 'Dark Pact', 50, 100, 50, 0);
insert into gem_weight(id, name, superior, anomalous, divergent, phantasmal) values(76, 'Spectral Shield Throw', 50, 100, 100, 20);
insert into gem_weight(id, name, superior, anomalous, divergent, phantasmal) values(845, 'Reap', 100, 50, 50, 0);
insert into gem_weight(id, name, superior, anomalous, divergent, phantasmal) values(75, 'Precision', 50, 10, 100, 0);
insert into gem_weight(id, name, superior, anomalous, divergent, phantasmal) values(6, 'Decoy Totem', 50, 100, 100, 10);
insert into gem_weight(id, name, superior, anomalous, divergent, phantasmal) values(9, 'Zealotry', 0, 0, 0,0);